---
  # Настройка производится на всех хостах
- hosts: all
  become: yes
  tasks:
  # Установка приложений на RedHat-based системах
  - name: install softs on CentOS
    yum:
      name:
        - vim
        - traceroute
        - tcpdump
        - net-tools
      state: present
      update_cache: true
   
  # Настройка будет производиться на хостах testClient1, testServer1, testClient2 и testServer2
- hosts: testClient1,testServer1,testClient2,testServer2
  
  # Настройка производится от root-пользователя
  become: yes
  tasks:
  
  # Добавление темплейта в файл /etc/sysconfig/network-scripts/ifcfg-vlan1
  - name: set up vlan1,2
    template:
      src: ifcfg-vlan.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-vlan1
      owner: root
      group: root
      mode: 0644
  
  # Перезапуск службы NetworkManager
  - name: restart network for vlan1,2
    service:
      name: NetworkManager
      state: restarted

  # Добавление файла конфигурации для настройки bond0
- hosts: inetRouter,centralRouter
  become: yes
  tasks:
  - name: set up ifcfg-bond0
    template:
      src: ifcfg-bond0.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-bond0
      owner: root
      group: root
      mode: 0644

  # Добавление файлов конфигураций для интерфейсов eth1 и eth2
  - name: set up eth1,eth2
    copy: 
      src: "{{ item }}" 
      dest: /etc/sysconfig/network-scripts/
      owner: root
      group: root
      mode: 0644
    with_items:
      - ifcfg-eth1
      - ifcfg-eth2

  #Перезагрузка хостов 
  - name: restart hosts for bond0
    reboot:
      reboot_timeout: 3600
